spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: "classpath:/sql/data.sql"
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
